spring:
  http:
    encoding:
      charset: UTF-8
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.69.3.116:3306/smartmeetingroom?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: OBUIVYyhm20010921.
  redis:
    database: 0
    host: 121.40.65.8
    port: 6379
    password: fengye..702
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        min-idle: 0
        max-idle: 8
    timeout: 5s

# 邮箱服务
  mail:
    host: smtp.qq.com
    username: 807920489@qq.com
    password: nongkygajkbibfji
    port: 25
  session:
    store-type: redis
logging:
  config: classpath:log4j2.yml

#设置不被拦截的uri
my:
  config:
    excludeuri:
      - /login
      - /register
      - /getcode
      - /error
      - /alterorganization
      - /getAllMeeting
      - /faceOpen
server:
  port: 8080
#邮箱服务